version: '3.8'

services:
  item-db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=item
    ports:
      - 5432:5432
volumes:
  postgres_data: